sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
- docker build -f Dockerfile.dev -t anchunliang/docker-react .
script:
- docker run -e CI=true anchunliang/docker-react npm run test
deploy:
  provider: gae
  keyfile: client-secret.json 
  project: oceanic-muse-269006
  skip_cleanup: true
  on:
      branch: master
